services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/rails
      - bundle_cache:/rails/vendor/bundle
    ports:
      - "3010:80"
    environment:
      - RAILS_ENV=development
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  storage: # ローカルでもGCSを使ってるので今は使わない
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443
    volumes:
      - storage_data:/data/assets # http://localhost:4443/storage/v1/b/assets/
    environment:
      - GCS_ENDPOINT=0.0.0.0:4443
      - GCS_NO_AUTH=true
      - GCS_DEBUG=true
    command: -scheme http -public-host localhost -data /data

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
  storage_data: