# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
with_host: &with_host
  <<: *default
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'db') %>
development:
  <<: *with_host
  database: server_development
test:
  <<: *with_host
  database: server_test
production:
  primary: &primary_production
    <<: *default
    database: server_production
  cache:
    <<: *primary_production
    database: server_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: server_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: server_production_cable
    migrations_paths: db/cable_migrate
