inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Style/Documentation:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

AllCops:
  Exclude:
    - 'app/graphql/server_schema.rb'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'config.ru'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'