name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs:
      client-diff-count: ${{ steps.check_diff.outputs.client-diff-count }}
      server-diff-count: ${{ steps.check_diff.outputs.server-diff-count }}
    steps:
      - name: check_diff
        shell: bash
        env:
          TARGET_BRANCH: ${{ github.base_ref }}
        run: |
          git fetch origin ${TARGET_BRANCH}
          count=`git diff origin/${TARGET_BRANCH} HEAD --name-only --relative=client | wc -l`
          echo "::set-output name=client-diff-count::$(echo $count)"
          count=`git diff origin/${TARGET_BRANCH} HEAD --name-only --relative=server | wc -l`
          echo "::set-output name=server-diff-count::$(echo $count)"
  frontend:
    runs-on: ubuntu-latest
    needs: check-diff
    if: needs.check-diff.outputs.client-diff-count > 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Install dependencies
      #   if: steps.diff.outputs.diff-count > 0
      #   working-directory: ./client
      #   run: npm install
  backend:
    runs-on: ubuntu-latest
    needs: check-diff
    if: needs.check-diff.outputs.server-diff-count > 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true
      - name: Run RuboCop
        if: steps.diff.outputs.diff-count > 0
        working-directory: ./server
        run: bundle exec rubocop